name: CI Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  latest:
    name: Test and lint latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: npm run tsc
    - run: npm run lint
    - run: npm run test

  next:
    name: Test next
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - run: npm install
    - run: npm install typescript@next
    - run: npm run tsc
    - run: npm run test
